//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormalLisReport
    {
        public int id { get; set; }
        public string hospnum { get; set; }
        public string patname { get; set; }
        public string Sex { get; set; }
        public string ext_mthd { get; set; }
        public string chinese { get; set; }
        public string check_date { get; set; }
    }
}
