//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDiagnose
    {
        public int id { get; set; }
        public string cardno { get; set; }
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public string Brithday { get; set; }
        public string CardId { get; set; }
        public string Icd { get; set; }
        public string Diagnose { get; set; }
        public string Type { get; set; }
        public string Flag { get; set; }
        public string DiagnoseDate { get; set; }
    }
}
