//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample_Clinical_Data
    {
        public int id { get; set; }
        public string sample_id { get; set; }
        public string sample_source_id { get; set; }
        public string created_at { get; set; }
        public string statu { get; set; }
        public string username { get; set; }
        public string update_at { get; set; }
    }
}
